"use client"
import { usePathname, useRouter, useSearchParams } from "next/navigation"
import { useEffect, useState } from "react"
type Option = { id: string; name: string }
export function BookingFilters({ branches, rooms }: { branches: Option[]; rooms: (Option & { branch: { name: string } })[] }) {
  const router = useRouter(); const pathname = usePathname(); const current = useSearchParams(); const [search, setSearch] = useState(current.get("search") ?? "")
  function update(key: string, value: string) { const params = new URLSearchParams(current.toString()); if (value) params.set(key, value); else params.delete(key); params.delete("page"); router.replace(pathname + (params.toString() ? "?" + params : "")) }
  useEffect(() => { const timer = setTimeout(() => update("search", search.slice(0, 80)), 350); return () => clearTimeout(timer) }, [search])
  return <div className="grid gap-3 rounded-2xl border border-white/10 bg-[#10131b] p-4 sm:grid-cols-2 xl:grid-cols-4"><input value={search} onChange={(e) => setSearch(e.target.value)} maxLength={80} placeholder="Mã, tên hoặc điện thoại…" className="rounded-xl bg-black/30 px-3 py-2" /><select defaultValue={current.get("status") ?? ""} onChange={(e) => update("status", e.target.value)} className="rounded-xl bg-black/30 px-3 py-2"><option value="">Mọi trạng thái</option>{["pending","confirmed","checkedIn","completed","cancelled","rejected","expired"].map((x) => <option key={x}>{x}</option>)}</select><select defaultValue={current.get("branchId") ?? ""} onChange={(e) => update("branchId", e.target.value)} className="rounded-xl bg-black/30 px-3 py-2"><option value="">Mọi chi nhánh</option>{branches.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</select><select defaultValue={current.get("roomId") ?? ""} onChange={(e) => update("roomId", e.target.value)} className="rounded-xl bg-black/30 px-3 py-2"><option value="">Mọi phòng</option>{rooms.map((x) => <option key={x.id} value={x.id}>{x.branch.name} · {x.name}</option>)}</select><label className="text-xs">Từ ngày<input type="date" defaultValue={current.get("from") ?? ""} onChange={(e) => update("from", e.target.value)} className="mt-1 block w-full rounded-xl bg-black/30 px-3 py-2" /></label><label className="text-xs">Đến ngày<input type="date" defaultValue={current.get("to") ?? ""} onChange={(e) => update("to", e.target.value)} className="mt-1 block w-full rounded-xl bg-black/30 px-3 py-2" /></label><select defaultValue={current.get("sort") ?? "createdAt"} onChange={(e) => update("sort", e.target.value)} className="rounded-xl bg-black/30 px-3 py-2"><option value="createdAt">Mới tạo</option><option value="startAt">Giờ bắt đầu</option><option value="status">Trạng thái</option></select><select defaultValue={current.get("order") ?? "desc"} onChange={(e) => update("order", e.target.value)} className="rounded-xl bg-black/30 px-3 py-2"><option value="desc">Giảm dần</option><option value="asc">Tăng dần</option></select></div>
}